#if !canImport(ObjectiveC)
import XCTest

extension SwiftHooksTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SwiftHooksTests = [
        ("testMessage", testMessage),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(SwiftHooksTests.__allTests__SwiftHooksTests),
    ]
}
#endif
