name: test
on:
- pull_request
jobs:
  xenial:
    container: 
      image: swift:xenial
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: swift test
  bionic:
    container: 
      image: swift:bionic
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: swift test
  thread:
    container: 
      image: swift:bionic
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: swift test --sanitize=thread
